POST http://localhost:5000/emails

Content-Type: application/json
{
    "email": "sahilchatiwala@gmail.com"
}

###

GET http://localhost:5000/emails

###

DELETE http://localhost:5000/emails/617b631053a576314d48d28e
###
